USER_QUERIES = { 
                  #   "distribution_channel" : "What are the distribution channels available for this policy like is this online-only, offline-only or online and offline both?",
                    "plan_options" : "What are the Plan Pptions available for the policy? Give brief description of each plan/benefit option.", 
                    "plan_description" : "What are the Key Features or Key benefits of the policy?",
                    # "plan_options" : "What are the key features of this policy ? Give brief description of each feature.",
                    # "min_age_at_entry" : "What is the Minimum age at entry for the policy(in years)? ",
                    # "max_age_at_maturity" : "What is the Maximum age at maturity for the policy(in years)?",
                    "minimum_sum_assured" : "What is the Minimum/Min. Sum Assured(Basic) for this policy?",
                    "maximum_sum_assured" : "What is the Maximum/Max. Sum Assured(Basic) for this policy?",
                    # "minimum_policy_term" : "What is the minimum policy term for this policy(in years)?",
                    # "maximum_policy_term" : "What is the maximum policy term for this policy(in years)?",
                    # "premium_paying_term" : "What is the premium paying term for this policy(in years)?",
                    # "minimum_premium" : "What is the minimum annual premium for this policy?",
                    # "maximum_premium" : "What is the maximum premium for this policy?",
                    "death_benefit_payment_option":"What are the death benefit payout/payment options? Include the rate details of the payout options.",
                    # "death_benefits": "Enumerate in detail the  sum assured on death for this policy.",
                    "death_benefits" : "What are the death benefits, Sum Assured on Death available for this policy for different plan options?For e.g - Death benefits is higher/highest of - .Stick to percentages and exclude specific amounts, included as examples in the policy document.", 
                    "other_benefits" : "What are the additional/optional/other benefits(if available) included in this policy ? For eg. child care, marriage, adoption,maturity, smart/special-exit benefit etc",
                    "exit_options" : "State the Exit values/options/benefits available for the policy for eg. Smart Exit Option? For eg. Smart/Special Exit Options etc. Exclude surrender benefits and paid-up value.",
                    "exit_option_conditions" : "What is/are the  Exit value/options/benefits terms/conditions for the policy?For eg. Smart/Special Exit Options etc. Enumerate the conditions under which the exit options can be availed/exercised.",
                    "surrender_value_factor" : "What is the Surrender value/benefit factor(SVF) or Policy Cancellation Value (PCV) Factor  for the policy?Include Unexpired Risk Premium like SSV, GSV if available.",
                    "surrender_benefits" :  "What is/are the Surrender value/benefits for this policy? Exclude paid-up value and exit options.Include Unexpired Risk Premium details of SSV, GSVif available",
                    "paid_up_value" : "What are the paid-up value/benefits available for this policy?",
                    "paid_up_death_benefit" : "What is the Paid-Up Sum Assured on Death available for the policy?",
                    "terminal_illness_benefits" : "What are the Terminal Illness (on diagnosis) benefits for the policy?",
                    "discount_online" : "What is/are the online channel discount/discounts available in this policy? Exclude discounts for salaried or existing customers.Provide relevant details.",
                    "discount_female" : "What is/are  the  discount/discounts/benefits for women/females in the policy?.Exclude any discounts for salaried or existing customers.",
                    "discount_existing_customers" : "What is/are the discount/discounts available for existing customers in this policy? For example - loyalty discount(s) etc. Provide relevant details.",
                    "discount_staff" :  "What is/are the discount/discounts available to the staff in this policy? Exclude any discounts for salaried or existing customers.Provide relevant details.",
                    "discount_salaried" : "What are the salaried customer discounts/benefits available in the policy?.",
                    "discount_high_sum" : "What is/are the high sum assured discount available in this policy? Exclude any salaried or existing customers discounts.Provide relevant details.",
                    "rider_benefits" : "What are the  rider benefits  available in the policy? Give brief description of each rider benefit.",
                    "instant_cash_benefit" : "What is/are the instant cash benefit(s) or claims available for this policy?",
                  #   "premium_payment_option" : "What are the premium payment options(e.g - Single,Regular,Limited) available for this policy?",
                  #   "premium_paying_term" : "What are the premium payment terms(PPT) (e.g - Single,Regular,Limited) available for this policy? Enumerate PPT details as present in the policy document.",
              }